config/routes.rb
Rails.application.routes.draw do
  resources :items
  post "add_to_list", :to => "items#add_to_list", :as => "add_to_list"
  get "store", :to => "invoices#store", :as => "store"

  resources :invoices
  get "toggle_item_in_invoice/:item_id", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice"
  get "toggle_item_in_invoice", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice_base"

  resources :payments, :debts
  get "payment_history", :to => "payments#history", :as => "payment_history"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  } 
  devise_scope :user do
    get "users/dashboard", :to => "users/sessions#dashboard", :as => "dashboard_sessions"
    get "users/:id", :to => "users/sessions#show", :as => "user"
    root "users/sessions#dashboard"
  end

    

end

app/models/debt.rb
class Debt < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :debtors
  has_many :users, through: :debtors
  has_one :invoice

  accepts_nested_attributes_for :debtors

  validates :amount, :numericality => { :greater_than_or_equal_to => 0 }

  def expense_everyone
    User.all.each do |user|
      debtors.create(:user_id => user.id)
    end
  end

  def users_share(user)
    total_shares = 0
    my_share = 0
    debtors.each do |debtor|
      total_shares += debtor.user.share
      if debtor.user == user
        my_share = user.share
      end
    end
    share_ratio = my_share / total_shares
    return amount * share_ratio
  end

  #implement later
  def running_total
    return nil
  end

  def to_s
    "#{owner.to_s}: #{description}"
  end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  #tmp, delete after initial dashboards
  def index
    @debts = Debt.all
  end

  def new
    @debt = Debt.new
  end

  def show
    @debt = Debt.find(params[:id])
  end

  def create
    @debt = Debt.new(debt_params)
    @debt.owner = current_user
    @debt.save
    debt_params[:user_ids].each do |uid|
      if integer? uid
        @debt.debtors.create(:user_id => uid)
      end
    end
    redirect_to dashboard_sessions_path
  end

  def edit
    @debt = Debt.find(params[:id])
    if @debt.owner.id != current_user.id
      redirect_to dashboard_sessions_path
    end
  end

  def update
    @debt = Debt.find(params[:id])
    if @debt.update(debt_params)
      redirect_to dashboard_sessions_path
    else
      render edit
    end
  end

  def destroy
    @debt = Debt.find(params[:id])
    if current_user.id != @debt.owner.id
      redirect_to dashboard_sessions_path
      return
    end
    @debt.debtors.each do |debtor|
      debtor.destroy
    end
    if @debt.invoice
      @debt.invoice.destroy
    end
    @debt.destroy
    redirect_to dashboard_sessions_path
  end


  private
  def debt_params
    params.require(:debt).permit(:amount, 
                                 :description, 
                                 :user_ids => []
                                )
  end
  
  def integer?(test)
    return true if self =~ /\A\d+\Z/
    return false
  end

end

app/helpers/debt_helper.rb
module DebtHelper
end

app/views/debts/edit.html.erb
<div class="group_area">
  <h1>Edit debt</h1>

  <%= form_for(@debt) do |f| %>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </div>
    <div class="field">
      <%= f.label :user_id, "Check all included:" %>
      <%= f.collection_check_boxes(:user_ids, User.all, :id, :to_s) %>
    </div>
    <div class="field">
      <input type="checkbox" id="select_all" value="select_all">Select all
    </div>
    <div class="submit">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/debts/index.html.erb
<div class="group_area">
<h1>Debts</h1>

<table>
  <tr class="table_header">
    <th>Description</th>
    <th>Amount</th>
    <th>Owers</th>
    <th>Owed</th>
    <th colspan=2> </th>
  </tr>
  <% @debts.each do |debt| %>
    <tr class="<%= cycle("odd_row", "even_row")%>">
      <td><%= debt.description %></td>
      <td><%= debt.amount %></td>
      <td><% debt.users.each do |user| %><%= user.first_name + " " %><% end %></td>
      <td><%= debt.owner.first_name %></td>
      <td><%= link_to :edit, edit_debt_path(debt) %></td>
      <td><%= link_to :delete, debt_path(debt), method: :delete,
                               data: { confirm: "Delete #{debt[:description]}?" } %></td>
    </tr>
  <% end %>
</table>

<br><br>

<%= link_to :New, new_debt_path %>
</div>

app/views/debts/new.html.erb
<div class="group_area">
<h1>New debt</h1>

<%= form_for(@debt) do |f| %>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id, "Check all included:" %>
    <%= f.collection_check_boxes(:user_ids, User.all, :id, :to_s) %>
  </div>
  <div class="field">
    <input type="checkbox" id="select_all" value="select_all">Select all
  </div>
  <div class="submit">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/debts/show.html.erb
<div class="group_area">
  <h1><%= @debt.description %></h1><br />
  <table>
    <tr>
      <td>Owner:</td>
      <td><%= @debt.owner %></td>
    </tr>
    <tr>
      <td>Debtors:</td>
      <td>
        <% @debt.users.each do |user| %>
          <%= user %></td></tr><td></td><td>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Amount:</td>
    <td><%= number_to_currency(@debt.amount) %></td>
  </tr>
  <tr>
    <td>Your share</td>
    <td><%= number_to_currency(@debt.users_share(current_user)) %></td>
  </tr>
  <% if @debt.invoice %>
    <tr>
      <td>Items on Invoice:</td>
      <% @debt.invoice.items.each do |item| %>
        <td><%= item.description.titleize %></td>
      </tr>
      <tr><td></td>
      <% end %>
    </tr>
  <% end %>
</table>
<br />
<br />
<%= link_to 'Delete', debt_path(@debt), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to 'Edit', edit_debt_path(@debt) %> |
<%= link_to 'Back', root_path %>
</div>