config/routes.rb
Rails.application.routes.draw do
  resources :items
  post "add_to_list", :to => "items#add_to_list", :as => "add_to_list"
  get "store", :to => "invoices#store", :as => "store"

  resources :invoices
  get "toggle_item_in_invoice/:item_id", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice"
  get "toggle_item_in_invoice", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice_base"

  resources :payments, :debts
  get "payment_history", :to => "payments#history", :as => "payment_history"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  } 
  devise_scope :user do
    get "users/dashboard", :to => "users/sessions#dashboard", :as => "dashboard_sessions"
    get "users/:id", :to => "users/sessions#show", :as => "user"
    root "users/sessions#dashboard"
  end

    

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  belongs_to :debt

  has_many :line_items
  has_many :items, through: :line_items

  accepts_nested_attributes_for :items
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @invoices = Invoice.all
    respond_with(@invoices)
  end

  def show
    respond_with(@invoice)
  end

  def new
    @invoice = Invoice.new
    respond_with(@invoice)
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.expensed = false
    @invoice.save
    respond_with(@invoice)
  end

  def update
    if params[:cost]
      @debt = Debt.create(description: "Store trip", amount: params[:cost], owner_id: current_user.id)
      @debt.save
      @debt.expense_everyone

      @invoice.expensed = true
      @invoice.debt_id = @debt.id

      @invoice.items.each do |item|
        item.needed = false
      end

      @invoice.save

      redirect_to root_path
    else
      @invoice.update(invoice_params)
      respond_with(@invoice)
    end
  end

  def destroy
    @invoice.destroy
    respond_with(@invoice)
  end

  #  def add_item_to_invoice
  #    @invoice = Invoice.find(params[:invoice_id])
  #    @item = Item.find(params[:item_id])
  #    LineItem.find_or_create_by(invoice_id: @invoice.id, item_id: @item.id).save
  #    respond_to do |format|
  #      format.js
  #    end
  #  end

  #  def add_item_to_invoice
  def toggle_item_in_invoice
    #@invoice = Invoice.find(params[:invoice_id])
    @invoice = Invoice.where(owner_id: current_user.id, expensed: false).first
    @item = Item.find(params[:item_id])
    @selected
    if @invoice.items.pluck(:id).include? @item.id
      @invoice.items.delete(@item)
      @selected = false
    else
      LineItem.create(invoice_id: @invoice.id, item_id: @item.id).save
      @selected = true
    end

    respond_to do |format|
      format.json
    end
  end

  def store
    @invoice = Invoice.find_or_create_by(owner_id: current_user.id, expensed: false)
    @items = (Item.where(needed: true) + @invoice.items).uniq { |x| x.id } .sort_by &:description
  end


  private
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:description)#, :invoice_id, :item_id)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.description %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @invoice.description %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/store.html.erb
<% @items.each do |item| %>
  <div data-itemid="<%= item.id %>" class="selectable <%= @invoice.items.pluck(:id).include?(item.id) ? "selected" : ""%>">
    <p class="big">
      <%= item.description %>
    </p>
  </div>
<% end %>
<div class="group_area zoomed">
<%= form_tag invoice_path(@invoice.id), method: "put" do %>
  <%= label_tag :cost, "Cost" %>
  <%= text_field_tag :cost %>
  <%= submit_tag "Expense" %>
<% end %>
</div>

app/views/invoices/toggle_item_in_invoice.json.erb
<%= { :selected => @selected }.to_json.html_safe %>