config/routes.rb
Rails.application.routes.draw do
  resources :items
  post "add_to_list", :to => "items#add_to_list", :as => "add_to_list"
  get "store", :to => "invoices#store", :as => "store"

  resources :invoices
  get "toggle_item_in_invoice/:item_id", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice"
  get "toggle_item_in_invoice", :to => "invoices#toggle_item_in_invoice", :as => "toggle_item_in_invoice_base"

  resources :payments, :debts
  get "payment_history", :to => "payments#history", :as => "payment_history"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  } 
  devise_scope :user do
    get "users/dashboard", :to => "users/sessions#dashboard", :as => "dashboard_sessions"
    get "users/:id", :to => "users/sessions#show", :as => "user"
    root "users/sessions#dashboard"
  end

    

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :line_items
  has_many :invoices, through: :line_items

  validates_uniqueness_of :description
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.needed = true
    @item.save
    redirect_to root_path
    #respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  def add_to_list
    @item = Item.find(params[:item_id])
    if params[:remove]
      @item.needed = false
    else
      @item.needed = true
    end

    if @item.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  #def store
  #  @items = Item.where(needed: true)
  #  @invoice = Invoice.find_or_create_by(owner_id: current_user.id, expensed: false)
  #end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:description, :item_id, :remove)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/store.html.erb
<% @items.each do |item| %>
  <div data-itemid="<%= item.id %>" class="selectable <%= @invoice.items.pluck(:id).include?(item.id) ? "selected" : ""%>">
    <%= link_to item.description, toggle_item_in_invoice_path(:item_id => item.id), :remote => true, :class => "list_link" %>
  </div>
<% end %>
<%= form_tag invoice_path(@invoice.id), method: "put" do %>
  <%= label_tag :cost, "Cost" %>
  <%= text_field_tag :cost %>
  <%= submit_tag %>
<% end %>